# -*- coding: utf-8 -*-
"""LecturaCorpus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RU88mo3651pHDsw7XL4tNXtDXpLIwivS
"""

import ast

def leer_documento_txt(archivo):
    documentos = []
    with open(archivo, 'r') as file:
        for linea in file:
            # Utilizamos ast.literal_eval para convertir la cadena en un diccionario
            documento = ast.literal_eval(linea.strip())
            documentos.append(documento)
    return documentos

archivo_txt = "corpus.txt"  # Nombre del archivo que contiene los datos
documentos = leer_documento_txt(archivo_txt)
for documento in documentos:
    print(documento)

len(documentos)

# Crear un conjunto para almacenar todas las palabras únicas en el corpus
palabras_unicas_corpus = set()

# Obtener el número de palabras y palabras únicas de cada documento y agregarlas al conjunto del corpus
for documento in documentos:
    palabras = documento['documento'].split()
    palabras_unicas_corpus.update(palabras)

# Número total de palabras únicas en el corpus
total_palabras_unicas_corpus = len(palabras_unicas_corpus)

#print(f"Número total de palabras únicas en el corpus: {total_palabras_unicas_corpus}")

import matplotlib.pyplot as plt

# Obtener el número de palabras de cada documento y del corpus
num_palabras_documento = []
for documento in documentos:
    num_palabras = len(documento['documento'].split())
    num_palabras_documento.append(num_palabras)

# Número total de palabras en el corpus
total_palabras_corpus = sum(num_palabras_documento)

# Crear gráfico de barras para mostrar el número de palabras en cada documento
plt.figure(figsize=(10, 6))
plt.bar(range(1, len(num_palabras_documento) + 1), num_palabras_documento, color='skyblue')
plt.xlabel('Documento')
plt.ylabel('Número de palabras')
plt.title('Número de palabras en cada documento')
plt.xticks(range(1, len(num_palabras_documento) + 1))

# Agregar el número total de palabras en el gráfico con letra más grande
plt.text(0.5, 0.95, f'Total de palabras: {total_palabras_corpus}', horizontalalignment='center', verticalalignment='center', transform=plt.gca().transAxes, fontsize=14, bbox=dict(facecolor='white', alpha=0.5))
plt.text(0.5, 0.85, f'Total de palabras unicas: {total_palabras_unicas_corpus}', horizontalalignment='center', verticalalignment='center', transform=plt.gca().transAxes, fontsize=14, bbox=dict(facecolor='white', alpha=0.5))
plt.show()

